language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t adighan/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true adighan/docker-react npm run test